name: Backstage PR Automation
description: Action to automate PR labeling and project updates
inputs:
  app-id:
    description: The Application ID of the GitHub App to use for authentication
    required: true
  private-key:
    description: The Private Key of the GitHub App to use for authentication
    required: true
  installation-id:
    description: The Installation ID of the GitHub App to use for authentication
    required: true
  project-owner:
    description: The organization that owns the ProjectV2 board
    required: false
    default: backstage
  project-number:
    description: The ProjectV2 number to sync against
    required: false
    default: "14"
  ignore-patterns:
    description: Comma or newline-separated regex patterns for files to ignore
    required: false
    default: yarn\\.lock$
  pr-number:
    description: PR number to process (defaults to PR from event payload)
    required: false
  label-added:
    description: Simulate a label being added (implies labeled action)
    required: false
  review-state:
    description: Simulate a review submission with this state (approved, changes_requested)
    required: false
  actor:
    description: Override for the actor (user who triggered the event)
    required: false
  action:
    description: The PR event action (e.g., opened, closed, synchronize, labeled)
    required: false
  priority-base:
    description: Starting priority value before size-based reduction
    required: false
    default: "100"
  priority-exponent-base:
    description: Base of the exponential decay (0.5 = halve priority per divisor)
    required: false
    default: "0.5"
  priority-exponent-offset:
    description: Lines of additions before priority starts decreasing
    required: false
    default: "0"
  priority-exponent-divisor:
    description: Lines of additions per halving of priority
    required: false
    default: "500"
  priority-reviewer-bump:
    description: Priority boost when PR has reviewer-approved label
    required: false
    default: "100"
  required-checks:
    description: Newline-separated list of required check names for priority calculation
    required: false
outputs: {}
runs:
  using: node24
  main: ./entry.js
