name: Backstage PR Sync
description: Action to sync Backstage PR tracking
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  board-number:
    description: The number of the project board to sync PRs towards
    required: false
outputs: {}
runs:
  using: node16
  main: ./entry.js
