name: PR Review Comment Trigger
on:
  pull_request_review_comment:
    types:
      - created

jobs:
  trigger:
    runs-on: ubuntu-latest

    # The PR re-review workflow will check the success status and only mark the
    # PR for re-review if this workflow did not fail.
    if: github.event.comment.user.id == github.event.pull_request.user.id

      # Inspired by https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number-${{ github.event.pull_request.number }}
          path: pr/
